### ISSUE TITLE
JW Library compatibility mode

### ISSUE THREAD

**Issue by thegadgetlad** [AntonyCorbett/OnlyT#151]
Our congregation would deeply appreciate a JW Library compatibility mode, which would allow media such as song lyrics, images and videos to display on the timer monitor, either as a PIP module in the corner or completely taking over the timer when specific media is played. The option of both would be even better. Many thanks.

**Comment by ucphinni** [comment]
Our congregation had similar needs but we went for a workaround that is
quite flexible.  To solve this, we display the OnlyT webclock at the bottom
of the screen and the second display on the chairman monitor via obs.

A second cheap solid state laptop drives the chairman monitor via OBS NDI
client to main computer with OBS NDI server.  Somewhat complicated because
our main computer only supports 2 active displays but mostly reliable, low
latency and works.

**Comment by thegadgetlad** [comment]
Thanks so much for the advice... tested the OBS method on my home PC and works a treat. I've advised the brothers. Saved us having to buy a dual input monitor.

**Comment by AntonyCorbett** [comment]
@thegadgetlad glad you have a solution. It's difficult to see how a suitable function could be built into the OnlyT application since it fundamentally involves another application (e.g. JW Library) mirroring its output. The use of OBS (see @ucphinni above) is ingenious!
