### ISSUE TITLE
Enlarge the clock

### ISSUE THREAD

**Issue by TiagoPaisAlmeida** [AntonyCorbett/OnlyT#17]
Hello. It is possible to enlarge the analogic clock to all the screen when no part of meeting is in course? Because this screen is the only clock of the hall.

**Comment by AntonyCorbett** [comment]
Perhaps as part of a configurable display that allows you to toggle some elements of the timer display on and off

**Comment by TechMan88** [comment]
yes an enlarge Analog clock would be nice, its a bit funny large tv and small clock. or the style soundbox had led numbers.. thank u Anthony

**Comment by donavan1** [comment]
Hi Just to throw this out there, An option in the screenshot predefined the start of the meeting ( countdown timer) then this is set to the TV only, at the end of the timer it switches back to the timer monitor at the back of the hall.

This is what I am test on a lab but would be a good Idea with countdown.

This is on the main PC,
![main pc](https://user-images.githubusercontent.com/8216036/31002296-12d3b7e4-a4ea-11e7-84c9-13a61ca5c779.PNG)

currently clock is displayed. only no background music.

When the meeting starts I switch it to the JW app play the song
![jw app screen switch on](https://user-images.githubusercontent.com/8216036/31002366-a29ceaee-a4ea-11e7-9bd6-fa49c9541f32.PNG)

Note: this is OK for a Weekend meeting but on the midweek there might be a bit of switching between the app, This is because of the videos.

**Comment by AntonyCorbett** [comment]
All done
