### ISSUE TITLE
Time summary on web clock or software

### ISSUE THREAD

**Issue by manuelvita96** [AntonyCorbett/OnlyT#174]
It would be nice to have a summary of the times of the meeting in progress, to clearly see how much time each speaker has used. It could be either on the web or software. Similar to a table, like InTempo/TimePlayer has

![1](https://user-images.githubusercontent.com/12810225/48419916-6a84e500-e759-11e8-93b9-e08aeeadae92.PNG)

**Comment by AntonyCorbett** [comment]
@manuelvita96 What's the purpose? Can the Timing report provide what's needed (see latest pre-release)

**Comment by manuelvita96** [comment]
The time report is generated at the end of the meeting, it would be useful to have a summary during the meeting to keep track of the times, for example in our congregation we use simultaneously two halls on different floors, the upper floor must synchronize with us to connect iin streaming with us for the final part of the meeting, seeing only the countdown is not very useful, if they delay or anticipate it creates confusion. A clear table with name and time is better

**Comment by AntonyCorbett** [comment]
@manuelvita96 Thanks. In the scenario you describe, I'm not sure I understand how a complete table of all talk times is helpful. Is the second hall a simple extension of the first, listening to the same speakers, or do they have different speakers? If they only join together for part of the program, who and how is syn controlled? Please would you expand on this, giving as much information as possible? Thanks, Antony

**Comment by manuelvita96** [comment]
Yes, i'm sorry, it's difficult to explain. In our kingdom hall on the ground floor the meetings are in Italian and on the top floor the various groups in foreign languages, about half of the meeting is done in different languages, so the various speakers follow the times that are assigned independently on different floors. Sometimes it happens that at the time of the streaming (the final part of the meeting is in Italian) we are not synchronized, having a table would allow us to clearly see which part of the meeting we are on the various floors. Using TimePlayer we see beyond the remaining time, also the name of the part and a complete table, this helps us to better understand at what point of the meeting we are. in the midweek meeting the parts are many and short, only with the remaining time can not be established certainty which part is in progress

**Comment by manuelvita96** [comment]
Yes it's correct. But with the web API it's complicated to do it, adding perhaps the name of the part to the web clock or creating a separate page (Like the first photo) would be easier

**Comment by AntonyCorbett** [comment]
@manuelvita96 how is the timer data to be transferred between halls?

**Comment by manuelvita96** [comment]
If you add the name of currrent talk on the web clock the operator need to open browser and see. Not everyone knows ho to use the Web API to get the data, this function needs to be simple. I don't know really how can do this in simple way

**Comment by AntonyCorbett** [comment]
@manuelvita96 Thank you. 

Adding the current talk to the web clock would reduce the size of the time display which many would find unacceptable. So this would need to be made available as an option. And that would mean that you couldn't have a web clock _with_ the talk name and another _without_, It's also a bit of a compromise in terms of your requirements.

So, what I'm suggesting is that the OnlyT web API makes _all_ the data that you need available in a form that a web developer might use to create a page to your exact requirements. This is one of the reasons I created the API - so that edge cases can be accommodated without having to complicate the software. This is an open source project, the API is well-documented (see https://github.com/AntonyCorbett/OnlyT/wiki/Programming-Interface-(API)), and the javascript skills needed to create such a web page are not uncommon.

Why not add an issue asking for help in creating the required web page via the API?

**Comment by manuelvita96** [comment]
Thank you! I try to study the Web API
