### ISSUE TITLE
Counsel duration for Ministry's last item miscalculated

### ISSUE THREAD

**Issue by LvDaniel** [AntonyCorbett/OnlyT#221]
Counsel and commendation duration of the last item on the Ministry section is showing "-1:00".
Although it's impossible to have the exact time for this (like it was in SonundBox) this should be estimated from the start of the next timer (Living - Part 1).

Please see below the timing report generated by the latest pre-released version (1.1.0.56).
[2018-12-05.pdf](https://github.com/AntonyCorbett/OnlyT/files/2656890/2018-12-05.pdf)
Thank you.

**Comment by AntonyCorbett** [comment]
@LvDaniel Thanks for the sample report. Just documenting here the bug with reference to your report. We have 2 significant base points - the end of the timer for "Predicare - Tema 3" (19:47:10), and the start of the timer for "Viața de creștin - Tema 1" (19:52:00). We must estimate both the duration of the "Interim Segment" and the duration of the final counsel section. Currently we hard-code a 3m 20s interim segment. In your report, since "Viața de creștin - Tema 1" starts at 19:52:00, we should assume that the Interim Segment started 3m 20s before, i.e. at 19:48:40. However, the report shows it starting at 19:47:25

**Comment by LvDaniel** [comment]
@AntonyCorbett Indeed. If you do some changes to address this in a later pre-release let me know and I'll test it. Thanks.

**Comment by AntonyCorbett** [comment]
Have "fixed" this by assuming that the counsel is on time. It's not great but there is no better method either.

**Comment by LvDaniel** [comment]
Souldn't assume that the mid song is on time (3:20) and the counsel to be the difference between Ministry-last-item finish time and Living-item1 starting time, excluding the song (3:20)?

**Comment by AntonyCorbett** [comment]
@LvDaniel We could do but the existing fix is somewhat easier. Both methods are estimations.

**Comment by LvDaniel** [comment]
Ok, I'll test it at tomorrow's meeting and if you like I'll provide feedback

**Comment by AntonyCorbett** [comment]
@LvDaniel Yes please

**Comment by LvDaniel** [comment]
@AntonyCorbett sorry for late response. Please see below the report from the previous week.
Looks better, but in fact the counsel duration was ~3 minutes, considering that the song was 2:10 (approximated by OnlyT to be 3:20) and the overtime of Interim segment +1:08.
More realistic would be to assume that Interim segment has a fixed value (3:20) and the counsel to be calculated from Ministry last item's end time and Living first item's start time. But if this is harder to implement, I think we can live with it.
[2018-12-12.pdf](https://github.com/AntonyCorbett/OnlyT/files/2696597/2018-12-12.pdf)

**Comment by AntonyCorbett** [comment]
@LvDaniel 

> More realistic would be ...

I'm sure your're right but if we can't be sure I think we have to give benefit of doubt to the chairman. Am closing now. Thanks for valuable feedback!
