### ISSUE TITLE
OnlyT and OnlyT remote app

### ISSUE THREAD

**Issue by richfrantz** [AntonyCorbett/OnlyT#229]
This is probably more of a curiosity, than a bug, but I CANNOT get the remote app to work if throttling is on. It works fine if throttling is off.
I don't know if something has changed on one side or the other, but thought I would report it. Just in case.

**Comment by LvDaniel** [comment]
@richfrantz & @AntonyCorbett I've noticed this also. Do you know how many devices are safe to run in order not to bring OnlyT to halt? Two or three it's safe? I assume that devices accessing through web clock should't matter, right? Thanks.

**Comment by AntonyCorbett** [comment]
@LvDaniel web clock is fine. The number of remote timers supported would depend on the PC and network. You'd need to experiment.

**Comment by LvDaniel** [comment]
@AntonyCorbett thanks, I'm gonna do that.

**Comment by moisestjsilva** [comment]
Good morning my brother, my name is Moses and I'm from Brazil, I do not know if this is the right place to ask about it, but I have two questions.
The first is if by chance the brother would have an example file of the file "talk_schedule.xml" using the "section" command because I could not use this command.
The second is to know what may be happening with the android app, because OnlyT works perfectly in IOS but on my android phone it does not connect.

If you can help me with these questions I will be immensely grade, follow below my email:
moisestj86@gmail.com.

**Comment by AntonyCorbett** [comment]
@moisestjsilva Thanks for your questions. This github page is the best place for support. You raise 2 questions:

1. Regarding your question about the OnlyT remote app on Android, ensure it is on the same network as your PC, and that the IP address, port and access code (if required) are set correctly. If it still does not connect, click the Exclamation mark symbol beside the "Verify Connection" action. This should display a dialog with an option to "TEST CLOCK WEBPAGE". Click this and check that your android device can display the OnlyT clock. Let us know how you get on.

2. Regarding your question about the manual talk schedule, please create a new issue so that we can discuss it without hijacking this thread.

Thanks
Antony
