### ISSUE TITLE
Disable Update button

### ISSUE THREAD

**Issue by elspag** [AntonyCorbett/OnlyT#231]
I don't know if it is possible, but can an option to hide update button (maybe in command line) be added? To all the Only suite?
This can be useful if there's someone in charge of taking care of the media system and don't want other friends getting the information and updating the apps.
Thanks

**Comment by richfrantz** [comment]
We don't have that issue because the congregations aren't running the PC under the admin account, thus can't install new versions.
They can see the arrow. They can click it, and download the update. When they try to install it, Windows prompts for the admin PIN/Password, which they don't have, and they hit the wall.
________________________________

**Comment by bergerchemical** [comment]
Exactly. You should implement the habit of using user accounts.

**Comment by AntonyCorbett** [comment]
Thanks for all your valuable feedback. However, I don't propose to implement this feature at this stage so I will close the issue. We have no idea what JWL developments will bring so I want to try to limit the feature-set of OnlyX applications to essentials. There appears to be a work-around discussed above.
