### ISSUE TITLE
Add meeting part title to Web Clock

### ISSUE THREAD

**Issue by timjobutler** [AntonyCorbett/OnlyT#238]
**Is your feature request related to a problem? Please describe.**
When the timer is in use, the Web Clock displays the timer only. However, there is no context as to what meeting part is being timed. 

**Describe the solution you'd like**
To provide context to the timer, it would be handy if the meeting part title was included above the timer. Many of our chairman prefer the Web Clock and having this extra data would be very beneficial.

**Describe alternatives you've considered**
No alternatives have been considered.

**Additional context**
While it maybe obvious what part is being timed if the user is following on with the meeting, the fast pace of the midweek meeting, especially the _Apply Yourself to the Field Ministry_ section, it is a handy reference to have to meeting part title available at quick glance.

**Comment by AntonyCorbett** [comment]
This applies to both the native timer display and the web clock.

**Comment by AntonyCorbett** [comment]
Any such enhancement would need to be optional because of the limited space often available, i.e. it would often be illegible (or make the actual timer digits too small).

**Comment by timjobutler** [comment]
@AntonyCorbett I did not realise that any changes to the web clock would be replicated to the native timer display.

Is it possible for it to optional (as you mentioned) and have a scaling setting for the text to match the same settings as the countdown clock? 

Just an thought without any idea of its feasibility.

**Comment by AntonyCorbett** [comment]
@timjobutler 

> I did not realise that any changes to the web clock would be replicated to the native timer display.

They don't have to be. I was just trying to flesh out your feature request.

**Comment by timjobutler** [comment]
@AntonyCorbett The feature request was originally intended for the web clock only

**Comment by AntonyCorbett** [comment]
@timjobutler understood. I enlarged upon your requirement because if it is to be implemented then it must be implemented in both native timer and web clock, otherwise someone will soon post a new feature request...

**Comment by ucphinni** [comment]
What about having it on its separate URL perhaps even in a shortened format. The Web Clock is currently at http://<ip>:<webclock port>/index
Parts could be at http;//<ip>-:<wedlock port>/part which would render the part similar geometry as the original web clock.
Additional config required would beAbility to turn on and off web clock partsShort, medium or long formatJustification: left, center, right autoFor 2: short should have 2 character mnemonic of part number and type, SONG type (e.g. sn) and number in the future. Also, a three character counsel part indication what could be employed,e.g cBR5 for counseling bible reading with counsel point number 5. I currently do not have a good feel for medium as it will be a mix between  long with full titles with some truncation. Long would have mnemonic with full titles and can be multiple lines. There may be a configurable minimum font size with this feature which would affect the geometry of what is rendered.
THIS would greatly help out the obs and ndi overlay users of onlyt

-------- Original message --------From: Antony Corbett <notifications@github.com> Date: 12/22/18  12:56 PM  (GMT-05:00) To: AntonyCorbett/OnlyT <OnlyT@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: Re: [AntonyCorbett/OnlyT] Add meeting part title to Web Clock (#238) 
Any such enhancement would need to be optional because of the limited space often available, i.e. it would often be illegible (or make the actual timer digits too small).

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/AntonyCorbett/OnlyT","title":"AntonyCorbett/OnlyT","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/AntonyCorbett/OnlyT"}},"updates":{"snippets":[{"icon":"PERSON","message":"@AntonyCorbett in #238: Any such enhancement would need to be optional because of the limited space often available, i.e. it would often be illegible (or make the actual timer digits too small)."}],"action":{"name":"View Issue","url":"https://github.com/AntonyCorbett/OnlyT/issues/238#issuecomment-449587587"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/AntonyCorbett/OnlyT/issues/238#issuecomment-449587587",
"url": "https://github.com/AntonyCorbett/OnlyT/issues/238#issuecomment-449587587",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by bergerchemical** [comment]
it seems to me that displaying additional information on the displays should be available as an option. so if someone had the conditions for this (eg a display of the right size), he can see what he wants..

**Comment by AntonyCorbett** [comment]
Thanks for all your valuable feedback. However, I don't propose to implement this feature at this stage so I will close the issue. We have no idea what JWL developments will bring so I want to try to limit the feature-set of OnlyX applications to essentials.
