### ISSUE TITLE
Custom Background on Countdown Timer

### ISSUE THREAD

**Issue by robisindy** [AntonyCorbett/OnlyT#252]
**Is your feature request related to a problem? Please describe.**
Not really a problem, but this would address a concern some may have regarding using the meeting countdown.

**Describe the solution you'd like**
Is there any chance that the option could be provided to have the meeting countdown display with a custom background, so that we could put the year text as the background and then size the timer so that the year text could remain on the monitors with the countdown in a corner of the screen?  This is the way our timer always appeared when using Soundbox, and it would be nice to be able to do this still.

**Comment by heltfeil** [comment]
Would it be possible to just make the countdown window be on top of the JWL media-window and either have the whole countdown window scale down to the actual size you choose for the countdown timer (instead of staying fullscreen black)? Or, if it's easier to implement; have the countdown fullscreen be transparent, outside the actual countdown (ie outside the area you already can choose to have bordered or borderless).  Maybe have it as an option, for those using the countdown on monitors that are not required to show the year-text at all times.
Until this is implemented, by the above suggestions or otherwise, I do not feel comfortable having no year-text in the kingdom hall for 5 minutes. Still useful on our timer monitor, but that's only visible from the platform.

**Comment by Danny1206** [comment]
This feature would also be perfect for our assembly, since the year text should be displayed. It worked well in Soundbox. The countdown was shown at the corresponding place above the year text. I would also welcome an adjustable time since 5 minutes too long. We worked with 3 minutes.

**Comment by KenFrantz** [comment]
I certainly agree with the suggestion to permit an alternate background to the countdown timer. The Kingdom Hall monitors look barren with the year text gone.

**Comment by AntonyCorbett** [comment]
@robisindy @KenFrantz @Danny1206 @heltfeil "Transparent background" is now available in the latest pre-release
