### ISSUE TITLE
Problem encountered: recalculation of the times

### ISSUE THREAD

**Issue by nicerose78** [AntonyCorbett/OnlyT#268]
By changing the time of the Bible study and the concluding comments, the program does not consider it recalculating the time of the study, while we need to recalculate it in consideration of the fact that the concluding comments will last longer.

**Comment by AntonyCorbett** [comment]
Thanks.  This was fixed in a recent release. What version are you using please?

**Comment by nicerose78** [comment]
V1.1.0.67

**Comment by AntonyCorbett** [comment]
@nicerose78 Thanks. Please would you describe the issue in greater detail? The bug that was fixed in the latest release relates to adaptive timing, but it's unclear whether this is what you are experiencing. Please let me know what your adaptive mode settings are (under "Automatic Mode"), describe how the item times were manually changed, and then what the results were during operation of the timers. Thanks, Antony

**Comment by AntonyCorbett** [comment]
@nicerose78 Thanks. What is your adaptive mode setting (under 'Automatic Mode') in OnlyT Settings please?

I assume that you manually adjusted the study timer to 20 minutes and it appeared as shown below:

![2019-01-18 12_09_07-s o u n d b o x - o n l y t](https://user-images.githubusercontent.com/24551146/51386333-f4ff1180-1b19-11e9-8c0d-76cda70a203a.png)

Notice that the default duration is 30 mins but it has been manually reduced to 20 mins.

> However, the program kept resetting the 24-minute study timer.

At what point did this happen? And what is the significance of "24 mins"?

**Comment by nicerose78** [comment]
In manual mode it works without problems while in adaptive mode it was not possible to set the timer to 20 minutes because the program restarted by setting the timer to 24 minutes. All of this happened at the beginning of the Bible study

**Comment by robisindy** [comment]
I'm just throwing something out there because I've been following this thread: Could this possibly have happened because the amount of time removed from the Bible Study was greater than the amount added to the Concluding Comments?  10 minutes cut from the study, but only 5 minutes added to the final part.  Was the adaptive timing kicking in to correct that?

**Comment by nicerose78** [comment]
Thanks @robisindy. it is possible but the meeting was very late so I could not add more time to the final comments

**Comment by AntonyCorbett** [comment]
@nicerose78 What is your adaptive mode setting (under 'Automatic Mode') in OnlyT Settings please?

**Comment by AntonyCorbett** [comment]
@nicerose78 The options (in English) are "none", "one-way" and "two-way". Since you state that the meeting was running overtime, it doesn't matter if it was one-way or two-way. I'll set up my test and get back to you asap.

**Comment by AntonyCorbett** [comment]
@nicerose78 my tests show there is still a problem here. Thanks for your report.

**Comment by nicerose78** [comment]
ONE way

Ottieni Outlook per iOS<https://aka.ms/o0ukef>
________________________________

**Comment by AntonyCorbett** [comment]
@nicerose78 Fixed in latest release. Thanks for your help.
