### ISSUE TITLE
Count up on web clock

### ISSUE THREAD

**Issue by ghost** [AntonyCorbett/OnlyT#32]
Some brothers I have talked to are not very comfortable with a count down. But they are more receptive to the stopwatch approach. Having this option on the web clock would be good.

**Comment by AntonyCorbett** [comment]
@omaha4 - agreed. Thanks for feedback.

**Comment by Stevo984** [comment]
Thank you for your good work. It will help us very much.

**Comment by donavan1** [comment]
Hi can the web clock be set to count up ?
this is an option. Reason because a brother giving a talk would like to know time lapse at certain part of his talk.

![webclock count up timer](https://user-images.githubusercontent.com/8216036/45083144-4b375f00-b0fb-11e8-922f-b35b29c1b1a5.PNG)

**Comment by phprelated** [comment]
Hi, 
The web clock not counting up is an issue on our end as well.
We use the application counting up (and we use it like this for many reasons), and we would like, if possible, the see in the web clock the same experience (right now it it is confusing if using the application counting up, but the web showing counting down...).

@AntonyCorbett is it possible to resolve this? 

Thanks a lot.
Csaba

**Comment by AntonyCorbett** [comment]
@Stevo984 @phprelated @donavan1 Please see latest pre-release

**Comment by Nickyes** [comment]
Thanks for all your excellent big work

Some speakers ask to show the counting differently from the settled one. Is not possible to change it when time is already started, but is very needed because often happen that the PC operator (now busier than before) forget this request before starting the counter and need to switch timer/stopwatch meantime the time is going. 

Please consider to add this implementation (if possible also to switch this on-going-behavior by the remote app)
