### ISSUE TITLE
Media screen mirror with timer overlay.

### ISSUE THREAD

**Issue by Spenser715** [AntonyCorbett/OnlyT#340]
**Is your feature request related to a problem? Please describe.**
I would like to possibly reopen an old feature request with an idea I had that I don't recall being explored. That feature is having a combination confidence and timer monitor in 1.

**Describe the solution you'd like**
I was thinking that it would be nice to be able to simply select a screen to mirror in onlyT settings then it would automatically overlay the timer on top of that selected screens contents (with position adjust settings as well). 

**Describe alternatives you've considered**
Right now we use OBS to do this but that often gets closed due to a difficulty in consistent training among the 3 congregations.

**Comment by ucphinni** [comment]
I’m curious, what difficulty have you had in training ?

We have 4 congregations. Each have a separate account. OBS projectors are set up to save on exit so the projectors are restored. 

There is also a hack in the main branch of OBS to allow websockets to bring up projectors on demand. I have not personally tested it but once this gets on the main release, I will be creating a script that controls the locations of the projector on the screen on startup. This would totally eliminate user error because the script would take control of projector placement.

Also,  I am already writing a script to display the onlyt timer window scene (not webclock) on obs when anything other than the yeartext is being displayed on the main screen..

From: Spenser715
Sent: Saturday, September 28, 2019 10:38 PM
To: AntonyCorbett/OnlyT
Cc: Subscribed
Subject: [AntonyCorbett/OnlyT] Media screen mirror with timer overlay. (#340)

Is your feature request related to a problem? Please describe.
I would like to possibly reopen an old feature request with an idea I had that I don't recall being explored. That feature is having a combination confidence and timer monitor in 1.
Describe the solution you'd like
I was thinking that it would be nice to be able to simply select a screen to mirror in onlyT settings then it would automatically overlay the timer on top of that selected screens contents (with position adjust settings as well).
Describe alternatives you've considered
Right now we use OBS to do this but that often gets closed due to a difficulty in consistent training among the 3 congregations.

**Comment by Spenser715** [comment]
The issue we have had is that since we do not shut down our computer (so as to allow Dropbox to automatically download public talk media) we simply close all programs except OBS when it is the appropriate time after a meeting. The issue we have is that since the projector window shows up on the taskbar some brothers think they are supposed to close it before turning of the displays. If you have an alternate suggestion for how to handle this setup I would love to hear it.

**Comment by ucphinni** [comment]
One way our cong tried was toolbar on each screen. The projector would be on the other screen.

That worked but looked clunky.

I have to check, but I think we just simply tell them to logoff (not shutdown). They know not to close programs because it does that for them.  We also have an auto logoff script.  I will check soon.

Sent from Mail for Windows 10

**Comment by ucphinni** [comment]
Ok.  Found out what we do.
We have explicit instructions to check the confidence monitor. If the confidence monitor does not have the onlyt projector, we have instructions to bring it up in the form of a document.

We also have a fix-it script which currently moves the screens to appropriate screens.  It can be run at any time, even during the meeting. This could easily be augmented. It currently detects the projector screen and moves it there if it is not there already. We do have the capability to send clicks to any app. In this case, for your fix, the following would be done.
Within the fix-it script

 If no projector screen being shown
• Grab OBS screen. Maximize it
• Right click on program area.
• Left click the FullScreen projector (Program Menu)
• Left Click Display 3.
• Restore the main  window to the appropriate location.
Else if projector screen found but on wrong screen or dimentions
• Put on screen 3 and size it to the entire screen

The more exotic way would to download the obs from master with the patch for websocket projector creation, create a script to connect to the websocket, send a request to create a projector window on display 3.
  

From: Cote Phinnizee
Sent: Saturday, September 28, 2019 11:38 PM
To: AntonyCorbett/OnlyT; AntonyCorbett/OnlyT
Cc: Comment
Subject: RE: [AntonyCorbett/OnlyT] Media screen mirror with timeroverlay.(#340)

One way our cong tried was toolbar on each screen. The projector would be on the other screen.

That worked but looked clunky.

I have to check, but I think we just simply tell them to logoff (not shutdown). They know not to close programs because it does that for them.  We also have an auto logoff script.  I will check soon.

Sent from Mail for Windows 10

**Comment by Spenser715** [comment]
Ok. Hmm would you possibly be able to email me spenserschafer715@gmail.com so we can discuss this more. I want to get our setup working so there will be no confusion from anyone.

**Comment by Spenser715** [comment]
Thank you brother for your help with the scripts for this. I am still curious if Antony would be able to add this feature to the onlyT app? This would still simplify the setup and remove the OBS factor altogether. Although I understand how to use it and scripts can help it is still very confusing for brothers who are not very technical.

**Comment by ucphinni** [comment]
Spenser715: Added this functionality to login script  for each congregation and it seems to work without non-technical brother’s knowledge that it even exists.

Question for Anthony, can the requested feature be copy display 2 whenever media is running? Not all congregations want overlays (I polled), but they are ok and prefer seeing on the confidence monitor 3  the onlyt window instead of yeartext, else anything shown on display 2. Spenser715’s overlay solution may be  good for during media playback under some circumstances, but overlays can get washed out and obscured muddying up the display. Imagine if an image or text is being displayed on the screen.

For your information, we are no longer using the webclock. Instead, we hid the true onlyt window on the 3rd monitor under the OBS projector window. OBS has configured in one of its Scenes to window capture and display the  onlyt window hidden under the OBS projector window. We have our script detect any changes on display 2, the script changes the scene to  the preconfigured OBS media scene and back when it detects yeartext again. 

The script is currently achieving this functionality through obs websockets. I am in the process of converting it to OBS API and making it a formalized OBS script instead so its more easily installable in obs and configurable.  If onlyt can do this work itself, I would forgo the script and OBS solution totally.

**Comment by centrallufkin** [comment]
@ucphinni I am very interested in the scripts that you are using. Would you be able to provide them with some very high level description of what they do? Thank you brother.

**Comment by Spenser715** [comment]
@centrallufkin here is a folder with all my scripts. I based the python script off of what @ucphinni gave me. Feel free to email me with any questions.

https://www.dropbox.com/sh/jvw1zoh70jcrlj5/AAAOevqmYBoL2StMfbTh1KtNa?dl=0

**Comment by ucphinni** [comment]
@centrallufkin The window moving script has been cleaned up dramatically by @spenser715. I would use that. To be frank, most development was done in spurts during and after the meeting when I was on sound as that was the time I had access to the system. His is much better organized. I was thinking of borrowing this script back since it is a lot cleaner and allow for a freeze mode where the script would detect its windows and store their positions. This would make it more user friendly and easier to setup.

He is also making smart use of autohotkey. Did not think of this. Finding correct location of each window is very specific to your setup of OBS and should be done this way, not in python as its fragile.  I’m going to follow Spenser in this aspect when I get a chance.

The one script which is nearly ready is the OBS auto scene switching one. It has a bug on start when OBS is not ready which I have to debug, but on manual start, it works. It requires obs websockets to be setup. I will deliver this to you when I next get access to the kingdom hall computer. However, I will be adding different features to it.

Roadmap
	0.9 Fix of startup issue.
1.0 instead of scene switching, will be doing show/hide sources within a single scene. (This helps when OBS being used to stream camera, This scene would be used to project to third screen)
1.1 Switch to media Program window automatically on media display and back to onlyt window on end.
2.0 Auto Digital crop to speaker in OBS

**Comment by ucphinni** [comment]
Here is a 0.9 version.

Installation:

   - Python 3.4 or above.
   - Install using pip install (as administrator) the following modules
      - opencv
      - numpy
      - numba
      - obs-ws-rc
   - Update the following lines in the script
      - Line 23: Audience monitor number (Normally 2, you can get this from
      right click, display settings and identify. The number will show
up on your
      audience monitor)
      - Line 26: Name of first start scene
      - Line 31: Name of scene to switch to when media is running
      - Line 35: Name of scene when yeartext is back up.
      - Line 95: The ip, port and password of your obs websocket.

The script attempts to detect and then remembers the yeartext screen. It
tries to ignore false positives by ignoring all black and colored
backgrounds on the audience monitor. However for best results, I would wrap
this script in a batch file to make sure the audience monitor has a stable
desktop before running.

I know I need to clean up the code a bit but was coding for functionality
first.  Would be nice to have heartbeats implemented some time in the
future so that the script can detect OBS went down. Script may not go down
with obs until next event.

import cv2
from mss import mss
import time
import numpy
import mss.tools
import time
import io
from numba import njit
import asyncio
import datetime
import sys

from obswsrc import OBSWS
from obswsrc.requests import SetCurrentSceneRequest

@njit
def index(array, item):
    for idx, val in np.ndenumerate(array):
        if val == item:
            return idx
    return None

monitor_number = 2
async def start_of_obs(ws):
    print("start obs")
    await ws.require(SetCurrentSceneRequest(scene_name="onlytwin"))


async def media_running(ws):
    print("media running")
    await ws.require(SetCurrentSceneRequest(scene_name="aud-mon"))

async def media_finished(ws):
    print("media finished")
    await ws.require(SetCurrentSceneRequest(scene_name="onlytwin"))
    
def static_pic():
    pass
def extract_corners_yr_txt(image):
    """
    Find the 4 corners of a binary image
    :param image: binary image
    :return: 4 main vertices or None
    """

    grey = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

    cnts, _ = cv2.findContours(grey,
                               cv2.RETR_EXTERNAL,
                               cv2.CHAIN_APPROX_SIMPLE)[-2:]
    x0,y0, x1,y1 = None,None,None,None
    
    for cnt in cnts:
        x, y, h, w = cv2.boundingRect(cnt)
        if x0 is None:
            x0,y0,x1,y1 = x,y,x+h,y+h
            continue
        
        if x0 > x:
            x0 = x
        if y0 > y:
            y0 = y
        if x + w > x1:
            x1 = x + w
        if y + h > y1:
            y1 = y + h
    return x0,y0,x1,y1

def scr_has_chged(sct,mymon,orig_img):
    new_img = numpy.asarray(sct.grab(mymon))
    d = numpy.array_equal(new_img,orig_img)
    if isinstance(d,bool):
        return not numpy.allclose(new_img,orig_img)
    b = index(d[:,:,0],False)
    return b is not None or index(d[:,:,1],False) is not None or index(d[:,:,2],False) is not None


def outer_image_change(sct,bmr):
    for monsec in bmr:
        if scr_has_chged(sct,monsec,monsec['img']):
            return True
    return False

def scr_look_for_mostly_black_img(sct,mon,min_per,max_per):
    total_pix = mon["width"] * mon["height"]
    img = numpy.array(sct.grab(mon))
    img2 = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    num_non_black = cv2.countNonZero(img2)
    percent = num_non_black / total_pix
    
    return (min_per <= percent and percent < max_per,img)

async def screen_record_efficient():
    try:
        ws = OBSWS('127.0.0.1', 4444, "secret")
        await asyncio.wait_for(ws.connect(), timeout=30)
        print("Connection established.")
        with mss.mss() as sct:
            mon = sct.monitors[monitor_number]
            big_monitor = {
                "top": mon["top"],
                "left": mon["left"],
                "width": mon["width"],
                "height": mon["height"],
                "mon": monitor_number

                }

            big_orig_img = None
            while True:
                most_black, big_orig_img = scr_look_for_mostly_black_img(sct,big_monitor,.01,.1)
                if not most_black:
                    await asyncio.sleep(1)
                    continue
                
                await asyncio.sleep(5)
                if not scr_has_chged(sct,big_monitor,big_orig_img):
                    break
            x1,y1,x2,y2 = extract_corners_yr_txt(big_orig_img)        
            x0,y0 = mon['top'],mon['left']
            x3,y3 = x0 + mon['width'], y0 + mon['height']
            bmr = []
            def bmr_add(sct,bmr,x0,y0,x1,y1):
                img = numpy.asarray(sct.grab(big_monitor))

                if y1 - y0 <= 0 or x1 - x0 <=0:
                    return
                m = {
              "top": big_monitor['top'] + y0,  
              "left": big_monitor['left'] + x0,
              "width": x1 - x0,
              "height": y1 - y0,
              "mon": monitor_number
                }
                m['img'] = numpy.asarray(sct.grab(m))
                bmr.append(m)
                    
            bmr_add(sct,bmr,x0,y0,x1,y1)
            bmr_add(sct,bmr,x1,y0,x2,y1)
            bmr_add(sct,bmr,x2,y0,x3,y1)
            bmr_add(sct,bmr,x0,y1,x1,y2)
            bmr_add(sct,bmr,x2,y1,x3,y2)
            bmr_add(sct,bmr,x0,y2,x1,y3)
            bmr_add(sct,bmr,x1,y2,x2,y3)
            bmr_add(sct,bmr,x2,y2,x3,y3)

            bmr0 = []
            bmr_add(sct,bmr0,x1,y1,x2,y2)
            monitor = bmr0[0]

            orig_img = numpy.asarray(sct.grab(monitor))
            await start_of_obs(ws)
            while True:
                print("static image on")
                while not scr_has_chged(sct,monitor,orig_img):
                    await asyncio.sleep(1)
                    

                showing_static_img = False
                print("static image taken down")
                while not outer_image_change(sct,bmr):
                    showing_static_img = not scr_has_chged(sct,big_monitor,big_orig_img)
                    if showing_static_img:
                        break
                    await asyncio.sleep(1)
        
                if showing_static_img:
                    await media_finished(ws)
                    continue
                
                await media_running(ws)
                
                while outer_image_change(sct,bmr):
                    await asyncio.sleep(1)

                await media_finished(ws)

    except asyncio.TimeoutError:
        print("OBS NOT RUNNING-- TIMEOUT!")

    except OSError:
        print("OBS IS NOT RUNNING")

    except:
        print(str(sys.exc_info()[1]))

    finally:
        await ws.close()
        print("Connection terminated.")

loop = asyncio.get_event_loop()
loop.run_until_complete(screen_record_efficient())
loop.close()

**Comment by AntonyCorbett** [comment]
> Thank you brother for your help with the scripts for this. I am still curious if Antony would be able to add this feature to the onlyT app?

@Spenser715 Sadly I don't think it's something that can readily be included in OnlyT

**Comment by Spenser715** [comment]
Brothers I am wondering is any of you have solved an issue with using khconf video and OBS as they can not both screen grab the same display at the same time to fulfill the confidence/timer combo we have been using and stream video?

**Comment by ucphinni** [comment]
I have not done this yet but you can attack this problem in multiple ways.

1. You use OBS only and copy the streaming url. The problem is emulating the encoding. For best results, use 720p2800 bit and be conservative about the encoding options.
2. You can use both. You can put OBS in portable mode. There is documentation online within the args section on how to do this.

**Comment by Spenser715** [comment]
I'm not sure if our video brothers would all be able to understand the standard OBS layout so option 1 probably isn't the best choice. I'm not sure I completely understand how option 2 would help, I see how to install it as portable but how would that allow both OBS and KHConf Video(a redesigned OBS) to grab the display.

**Comment by ucphinni** [comment]
I have not run khconf video on a standard setup. I am looking at it now on my 1 display laptop. I don't see where there would be a problem. Could you explain it to me? I was thinking that there was a conflict not because of the screen but because of the registry. Im probably wrong. 

Does khconf video require an extra screen?

Also, #1 is viable because you can make it look very similar to khconf.  Let me try and I will create a snapshot.

**Comment by Spenser715** [comment]
So the issue is that 2 instances of OBS(and since khconf is just modified OBS it counts) cannot display capture the same display. So since the confidence/timer OBS is capturing the media monitor then the khconf app will not get any image. If you start khconf first it will start with an image, but then when you switch to camera and back to computer it will just be a black screen (if you have OBS running for confidence/timer monitor)

**Comment by ucphinni** [comment]
![Capture](https://user-images.githubusercontent.com/5283004/68824304-6fc68980-0664-11ea-976d-a8f5c0fea319.PNG)

**Comment by ucphinni** [comment]
OBS has the browser.  with some scripting, one can do the event log and make the buttons on the right side to confirm to khconf video, but this is a good first shot.

**Comment by Spenser715** [comment]
Ok so can we recreate the multi congregation section of the khconf app too? We have 3 congregations so we would need that.

**Comment by ucphinni** [comment]
You can use scene collection for the time being.  This is functionally equivalent.
More than that, you would require scripting once again.  You can make it look exactly like khvideo with the exception of hiding the menu bar.  You can do this because the built in web browser can be shown in as a doc. Since you can use a scripting language like python and it can communicate back to the OBS using OBS web sockets, all buttons can be simulated through web browser calls.

When I have time, I would be interested in creating such a local web server which one can utilize.

**Comment by Spenser715** [comment]
OK so I have been able to figure out how I can use 1 instance of OBS but I'm worried about 2 things. First, will scene collections be easy for all brothers to be able to operate? We don't want this to be too complicated that we need to spend too much time training for it. Second, Is there a way to hide a scene from the scenes menu? In order to use 1 instance of OBS I need 1 scene to be the Confidence/Timer scene that gets projected, however I don't want this to get accidentally streamed during the meeting.

**Comment by Spenser715** [comment]
OK so i was playing around a bit more and happened upon an interesting discovery. the KHConf stream app does screen grab at the same time as OBS. The only issue is that it will sometimes glitch and not show the year text. It does still grab the screen and you can see this if your cursor goes on that screen, it is just something with the year text. So if you are either just leaving it on computer feed or switching back and forth for videos and images it should work just fine.

**Comment by ucphinni** [comment]
THere is no native way to hide a scene. You can hide sources, but not scenes. Here again, webserver scripting with  websockets can fill this gap.  The only thing that cant be done using this approach is hide the menu bar.

Also the confidence scene accidental click can be mitgated by going into studio mode.  However, this is more compliated and advanced.

> OK so I have been able to figure out how I can use 1 instance of OBS but I'm worried about 2 things. First, will scene collections be easy for all brothers to be able to operate? We don't want this to be too complicated that we need to spend too much time training for it. Second, Is there a way to hide a scene from the scenes menu? In order to use 1 instance of OBS I need 1 scene to be the Confidence/Timer scene that gets projected, however I don't want this to get accidentally streamed during the meeting.
