### ISSUE TITLE
3 seperate monitors stay in home positions ?

### ISSUE THREAD

**Issue by soundmanmike** [AntonyCorbett/OnlyT#351]
I use  3 monitor configurations .
1 Is the main monitor for working from  
2.Is for projecting media to several TV Monitors running through a HDMI to cat5e conversion For the congregation to see. These two really no problems at this time but when I try to introduce a third monitor to run Only T through and this monitor is to be for speakers only to see I have problems .Each time the system is powered up the monitors shift .I need to designate each one for their own home position .
Any ideas ? Software ,Hardware ?

**Comment by bergerchemical** [comment]
We have a similar hardware solution: a monitor with sound system, a projector for the auditorium (but soon two screens) and a dedicated monitor at the back of the room for displaying time using OnlyT. The whole is supported by Nvidia GeForce GTX 1660. We didn't have major problems yet. As far as I remember, the monitor configuration fell apart twice, but after the reset everything returned to normal. If you have specific questions, I am happy to help, greetings :)

**Comment by AntonyCorbett** [comment]
This from a post in the OnlyM project:

When this happens then you see the behaviour you describe - displays may be enumerated in a different order on each boot (unless you leave devices physically connected and in standby mode). There are a few options as follows:

Update your video driver to see if it correctly reports the monitor names (in which case the monitor list will show names rather than device designations).
1. Leave monitors on standby and check that the video driver consistently enumerates them in the correct order.
2. Use third-party software (e.g. https://www.nirsoft.net/utils/multi_monitor_tool.html) to manage multiple monitors.
3. Use an EDID hardware device to maintain an identifiable "connection" to your monitors even when they are turned off.

**Comment by AntonyCorbett** [comment]
@bergerchemical Closing for now, but please reopen the issue if necessary.

**Comment by soundmanmike** [comment]
Thank you, I will try your suggestion

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by bergerchemical** [comment]
@AntonyCorbett  ok thank you
