### ISSUE TITLE
Monitor configuration

### ISSUE THREAD

**Issue by fcolista** [AntonyCorbett/OnlyT#367]
Hello, thank you for this great software.
I'm wondering if it's possibile to define manually the monitor for countdown via file or registry.
With latest OnlyT version and Windows 1909 update, we have observed that OnlyT (and OnlyM) loose the setting of the monitor when started.
Thanks a lot.
.: Francesco

**Comment by AntonyCorbett** [comment]
@fcolista This problem is usually caused when Window Update changes your video driver. Please check it is up-to-date, referring to the manufacturer's websire rather than letting Windows choose a driver. There is a command-line option in OnlyT to specify the monitor (and countdown monitor). See the wiki for more information.

**Comment by fcolista** [comment]
Thanks for your answer.
Beside the command line option, there's a place where this information is written?
File or reg key?
Thanks.

**Comment by AntonyCorbett** [comment]
>Beside the command line option, there's a place where this information is written?

The monitor can be selected in OnlyT settings (which is stored in the app's settings file), but this won't help you because of the problem with the driver
