### ISSUE TITLE
Time reports

### ISSUE THREAD

**Issue by AlexSanti** [AntonyCorbett/OnlyT#381]
It sometimes happens at weekend meetings that the speaker is late and the meeting has to start with The Watchtower. When changing the sequence of the meeting, it appears that at the end the program does not save the report.
The same happens in the week's meeting if for any reason the sequence of appointments is changed.
Is there a solution?
Thank you very much for your hard work.

**Comment by AntonyCorbett** [comment]
@AlexSanti I believe this only happens if the final item on the agenda is replaced with an earlier item. The production of the report occurs when the final item (the WT study on weekends) finishes. At this stage OnlyT evaluates the timers and determines whether the times are reasonable. In the case you describe, OnlyT would deem the times to be invalid and skip the timing report. 

We could delay the report writing until all timers have been used (regardless of sequence), but this would not work if one or more talks were not timed for some reason. Any other suggestions welcome,

**Comment by AlexSanti** [comment]
That's exactly what happens.
It is an unusual situation, but for example it happened last weekend.
What if, if necessary, is it possible to manually create the meeting parts?
For example, in the case that happened over the weekend, we could manually create the meeting with The Watchtower first 60 minutes following the Public Speech 30 minutes.
So the program would see it as normal.

**Comment by AntonyCorbett** [comment]
Reports are only generated for auto mode, not for manually generated timers.

**Comment by AlexSanti** [comment]
So I don't see how we can have reports with changes to the meeting order, as it can happen.
Soundbox made this possible and the report was still made.

**Comment by AntonyCorbett** [comment]
@AlexSanti correct, that's how it currently works.

**Comment by TizianoNoto** [comment]
> Reports are only generated for auto mode, not for manually generated timers.

Do you think it's possible to include the file based mode?

**Comment by AntonyCorbett** [comment]
@TizianoNoto You should add a feature request here (as a separate issue), but unless there's a big demand I think it would be low priority.

**Comment by AntonyCorbett** [comment]
@AlexSanti Sorry, I deleted your pull request. They are used only for submitting code changes to the repository. Please add an Issue instead.
