### ISSUE TITLE
Remote control

### ISSUE THREAD

**Issue by Drizztfire** [AntonyCorbett/OnlyT#40]
Hi,
I understand that it's not simple and would require a lot of time to integrate ... 
The remote control function is really usefull and allow us to use brothers for sound that would not be able to multi-task and manage the timer.

With the remote control in Soundbox we can use another brother who manage the timer from his place.

Thanks

**Comment by ucphinni** [comment]
Remote control may be simplified if an embedded web server is used.

A minimal functionality to displayed on connection to OnlyT/remote could be:
  Current Part Name
  Next Part Name: {Empty if at end of meeting, may be equal to current part if stopped}
  Status: Can be Started or Stopped

  Stop button to stop the current part and auto advance  to next part.
  Start button to start the current part.

Start and stop buttons may be combined to one button or grayed out appropriately but this functionality may be dropped in order to expedite this feature.

**Comment by lukeclifton** [comment]
Hi @AntonyCorbett. Thanks for your work so far with OnlyT & OnlyR. We've just started using it and they work great.

Remote control functionality is something we also need. I am a web developer who also has experience building mobile apps with ReactNative and Ionic.

If / when an API becomes available i would be happy to help develop a remote control app. Do you have any timeframe in mind for an API?

**Comment by AntonyCorbett** [comment]
@lukeclifton - thanks for your offer. I've no definite plans to add remote support a this stage.

**Comment by MattDelmarter** [comment]
I also would love to see the timer remote API available, assuming it would be similar to the SoundBox remote API. Then I can port the [SoundBox Remote](http://soundbox.imattsolutions.com/) app to work with Only T :)

**Comment by Drizztfire** [comment]
@AntonyCorbett Your the best ! Thanks !

**Comment by AntonyCorbett** [comment]
The latest pre-release contains the API code, but documentation is not yet available.

**Comment by AntonyCorbett** [comment]
Documentation and an updated pre-release are now available. I am closing the issue.

**Comment by K0rTy** [comment]
Hi, is there a possibility for an Android version?

**Comment by MattDelmarter** [comment]
@K0rTy There is a possibility yes but no promises at this stage.

**Comment by K0rTy** [comment]
@MattDelmarter 

Android platform is more common here in my region of Brazil.
