### ISSUE TITLE
Stand alone operation via windows Tablet 

### ISSUE THREAD

**Issue by jurena015** [AntonyCorbett/OnlyT#41]
At our hall we have two front TVs  for audiences and rear tv for the elders to see images and song lyrics plus timer, all control from one pc. The plan is to install another tv, seperated From the sound system to always have only t app active at all time from a windows tablet connected via hdmi. And possibly have a two brothers work the sound system. Can this app work on windows tablet ? Will this app be available for android or iOS ? Would love to use miracast or airplay to wirelessly remote control the app. ( as long as tv support micracast and onlyT works on windows Tablet I don’t see why micracast won’t work) 

Thank you. 

Open to any suggestions.

**Comment by omaha4** [comment]
I can vouch that OnlyT does work on a Windows 10 tablet. You can also mircast to a Microsoft Wireless adaptor as an affordable solution. That being said, a word of caution. While mircasting works flawlessly on my Lenovo 2 in 1, OnlyT has problems casting from my Surface Book to the MWA in extended desktop mode.  Only when I hook up to a third monitor does the OnlyT see the MWA correctly. The same would probably be true for a Surface Pro 4 since it shares common hardware with the Surface Book. As always, while hard wired connections are preferred in mission critical environments, more casting can be done on the cheap.

**Comment by AntonyCorbett** [comment]
@omaha4 thanks for response. @jurena015 I can confirm that you should be able to run on any Windows 10 device. Would recommend wired connection to monitor.
