### ISSUE TITLE
Speaker message

### ISSUE THREAD

**Issue by fcolista** [AntonyCorbett/OnlyT#412]
Hi!
This is to re-open a feature request that has become offtopic and (correctly) closed: https://github.com/AntonyCorbett/OnlyT/issues/39
Would be very useful to get this feature.
Thanks.

.: Francesco

**Comment by Wistula** [comment]
Hello, we are also in favor of a short commentary for the Speaker. I found some indirect way to do this. at OnlyV
1. Create a new theme
*black background
*white text(or other), no verses.
*The name of the book should be set as the background so that it is not visible.
*We adjust the size of the text individually.
2. In onlyV, we choose our theme.
3. Select the time monitor in the OnlyV settings
4. Check the option to allow the editing of the verses
5. Open Genesis 1: 1, and change to our text. we provide a speaker

**Comment by Nickyes** [comment]
We don't use OnlyV but i was asking to send a message in timer monitor, (generally 3rd one), the monitor that is in front of the speaker in Hall, not in the second (the monitor that all people see)

**Comment by AntonyCorbett** [comment]
@Nickyes - I believe the suggestion from @Wistula was to use OnlyV and set the output monitor to the timer monitor.

**Comment by Wistula** [comment]
We also do not use OnlyV in our meetings to display the verses.  Therefore, in the OnlyV settings, I set Monitor 3 (the one where the time is displayed only for the speaker).  It serves us only and exclusively to communicate to the speaker.

**Comment by Nickyes** [comment]
> @Nickyes - I believe the suggestion from @Wistula was to use OnlyV and set the output monitor to the timer monitor.

Since we do not use I ignored that can send OnlyV output to the timer monitor, sorry :)
