### ISSUE TITLE
Timer Bell on Ministry items

### ISSUE THREAD

**Issue by StuffbyJoc** [AntonyCorbett/OnlyT#417]
Hiya
First off, awesome software, really appreciate your work on it. Just discovered tonight that the timer no longer rings when items go overtime. It works for the Bible reading, however, "Ministry- Item 2", and, "Ministry - Item 3" do not work anymore. This is the first time it has happened, for the midweek meeting of January 4-10th. Is this a change for 2021 or is it an error we are experiencing? Much appreciated,
Jesse

**Comment by AntonyCorbett** [comment]
@StuffbyJoc Thanks. Yes, this is a bug in the feed that provides talk times, etc. I have now fixed it. However, since the feed is cached locally it will take a few days to refresh on your PC. Alternatively you can force an update by closing OnlyT, and removing the feed,json file from this folder: %AppData%\OnlyT

OnlyT will then download a fresh (fixed) copy.

**Comment by sewru** [comment]
Thanks for fixing, was scratching my head what I did wrong with the config settings. Everything is working now.

Many thanks and Stay safe my brother

**Comment by StuffbyJoc** [comment]
Thanks so much for that. Appreciate your work on it and your quick response on how to fix it!
