### ISSUE TITLE
Counsel timers for midweek meeting

### ISSUE THREAD

**Issue by barrymichels** [AntonyCorbett/OnlyT#464]
The counsel times are shown on the report, but it would be nice to have a 1 minute timer the chairman can start after each student part. It could be enabled by an option so those that don't want to use it can hide those timers.

**Comment by AntonyCorbett** [comment]
@barrymichels Whenever counsel is to be offered, after the student timer is stopped, the display shows how long the student talk took. This static display remains on-screen for a little over 1 minute so that the chairman can refer to it if needed. When the minute is up, the timer display reverts to the standard clock - giving the chairman notice that his 1 minute is up. It's simply a matter of training the chairman to understand these cues.

See Settings => Automatic Mode => Persist student time

**Comment by barrymichels** [comment]
That's good to know and might be a good reason to install a display for the timer.
We use a large format standard clock and do not use the timer display. Just the app on the chairman's phone and the OnlyT program on the console/media player PC.

**Comment by AntonyCorbett** [comment]
@barrymichels Please see the latest release, which now includes a "Show persist countdown bar" option that can be used with the "persist student time" option to display a countdown bar for the chairman during counsel.
