### ISSUE TITLE
Time is not displayed correctly

### ISSUE THREAD

**Issue by alanfermtz** [AntonyCorbett/OnlyT#519]
**Describe the bug**
some weeks ago and this week we notices that some parts entries does not appear correctly the needed time.

**To Reproduce**
it happens on fresh installation and previous installation.

**Expected behavior**
To be exact the time

**Screenshots**
![imagen](https://github.com/AntonyCorbett/OnlyT/assets/43801184/cb190c73-3e67-43ab-a876-655ce72058c7)

**Desktop (please complete the following information):**
 - Windows 10 and 11
 - OnlyT 2.2.0.5

**Comment by MiltJR111** [comment]
I was about to come here and report the same thing. We had our meeting last night and the second Living As Christians part was missing from the remote app. I'm wondering if there's a set number of parts that are expected for the overall meeting, and since there was an extra one in the Field Ministry section, if then there wasn't enough remaining parts for the 3 in Living As Christians.

At any rate, if it can be easily fixed, it would definitely be appreciated!

**Comment by AntonyCorbett** [comment]
@alanfermtz @MiltJR111 Yes, this is a bug. I will be able to fix it for next week.

**Comment by SemSemmo** [comment]
> @alanfermtz @MiltJR111 Yes, this is a bug. I will be able to fix it for next week.

Hi Antony, is there any news on the update?
Thank you in advance for your work in developing these useful meeting software :)

**Comment by MiltJR111** [comment]
In the interim, on weeks where the parts don't align with OnlyT, I've just been using a manual talk_schedule.xml, but that has the unfortunate side effect of not saving a Timing Report and the inability to adjust to the meeting time if early parts have gone overtime.

So ideally having it fixed on the back-end would be better (although having options to handle the above situations would be nice too). No worries, though, since we're all very busy (especially today).

**Comment by AntonyCorbett** [comment]
It was fixed a few weeks ago. I should have updated this bug report. The fix is in the feed rather than in the application. If you are still experiencing issues, please delete the cached feed so that OnlyT picks up the latest data.

**Comment by SemSemmo** [comment]
> It was fixed a few weeks ago. I should have updated this bug report. The fix is in the feed rather than in the application. If you are still experiencing issues, please delete the cached feed so that OnlyT picks up the latest data.

How can i delete this cached feed?

**Comment by AntonyCorbett** [comment]
@SemSemmo The cached feed is the file named feed.json in this folder on your PC:

%AppData%\OnlyT

Just close OnlyT, delete the file and re-open.
