### ISSUE TITLE
JW Library

### ISSUE THREAD

**Issue by angelodel95** [AntonyCorbett/OnlyT#52]
when trying to play a video on JW Library using this timer the computer gets completely confused. It does not display any media from JW library with the timer.

**Comment by ricardoantonio** [comment]
@angelodel95 Sorry, I don't understand your issue. OnlyT and JWL are a independent applications. In OnlyT you need to select in the config panel the display device visible to the speaker. Remember, WTL always show the media in the second monitor. Can you be more specific?

**Comment by angelodel95** [comment]
When we used JW library with this timer, JW library was not playing any
videos. I had to exit out the timer and then on jw library click on the
extend to second display again in order for us to show any video. Once I
exited out of the timer JW library was working normal. Hard to explain in
email I am sorry.

**Comment by ricardoantonio** [comment]
I think your problem is how to connect the screens to the computer. I don't speak English very well, I speak spanish, if you need help find me ok Twitter as @rantoniomx.

As i can see this not a OnlyT issue.

**Comment by TechMan88** [comment]
Grt Job Anothony love Only T. Is there a way to disable the settings so others dont change things around? I wish the download button was in setting and has the option to be locked.

Sent from Yahoo Mail on Android 
 
  On Thu, Jan 18, 2018 at 9:15 PM, Ricardo Antonio<notifications@github.com> wrote:   
I think your problem is how to connect the screens to the computer. I don't speak English very well, I speak spanish, if you need help find me ok Twitter as @rantoniomx.

As i can see this not a OnlyT issue.

**Comment by AntonyCorbett** [comment]
@angelodel95 - it sounds like you are using the same monitor to output content from JWL _and_ the timer from OnlyT. This will indeed cause some issues. OnlyT is designed to have exclsuive use of a 3rd monitor.

**Comment by AntonyCorbett** [comment]
@TechMan88 - thanks for feedback. See #43. Thanks, Antony.
