### ISSUE TITLE
Stuck on 'Always on top'

### ISSUE THREAD

**Issue by UNiXMIT** [AntonyCorbett/OnlyT#69]
I'm not sure what's going on but I can't get the OnlyT window to not be always on top. The check box for this option is not ticked. I've tried ticking then un-ticking the option. Ticking the option, closing down the program, opening it again then un-ticking and closing and re-opening again. It never wants to hide. I have to minimise it. OnlyM and OnlyR play nicely and don't do it, they can be set to the background.

Testing on a Windows 10 VM it works fine so not sure what's going on. Any ideas?

I am running the latest version too.

Thanks

**Comment by AntonyCorbett** [comment]
@UNiXMIT I suspect the timer window is displayed, in which case the app always stays on top to prevent it getting stuck behind the timer window. OnlyM behaves in the same way. I'll make a note in the wiki

**Comment by UNiXMIT** [comment]
Ah ok that makes sense. Thank you

**Comment by Chipperchap** [comment]
My understanding is that some don't use OnlyT to display a timer on a particular fixed screen, such as at the rear of the auditorium for the speaker (talker), but rather only on a portable device such as a tablet or a phone.  (We do both).  
For the mobile only instance, the option to disable **_always on top_** is great. 
However for those that use a fixed secondary screen there is no way to effectively 'disable' **_always on top_** as it is overridden by the 'safety' feature of not losing the application window behind a display screen (such as incorrectly choosing the PC monitor instead of the timer screen/monitor).  
The difficulty is that there is limited screen estate when multiple apps are open, and when an app is moved around or expanded in size, such as when using OnlyV or similar, OnlyT _gets in the way_ as it were as it is **_always on top_**.  
Since OnlyT already has the ability to find additional screens connected to the PC, could the following ponderisms be proffered: 
- Perhaps the user could be 'warned' that the timer display screen ((or countdown screen) selected is the same as the one the app window is using which cannot be done without remaining on top.
- Or perhaps it could enter a 'mini view' similar to the windows media player app, so that it can be 'expanded' or 'maximized' with the click of a toggle.
![](https://i.postimg.cc/nz3nxNv3/screenshot-602.png)

Not a biggie, just wondering 😄
