### ISSUE TITLE
Countdown for beginning

### ISSUE THREAD

**Issue by asgardi01** [AntonyCorbett/OnlyT#80]
Actually, the 5-minute countdown till the beginning of the meeting is not displayed on the 2nd monitor, if you don't activate the output monitor for everything in the app.
We do not display the timer generally on the 2nd monitor in the front - jwlibrary is displayed with the year-text on this 2nd monitor - therefore, the monitor option is set to none in onlyT.
Would it be possible to make onlyT as compatible with jwlibrary as onlyM is already regarding the display of active content?
It would help us a lot and would make the application even more usefull, if the countdown to the beginning of the meeting would be displayed on the 2nd monitor, even if jwlibrary is active and is streaming the standard year-text to this monitor, AND the countdown should be displayed although the timers etc are not wanted to be displayed on the 2nd screen (we only use the web-counter for the speaker, therefore we have to disable the timer output on the 2nd screen but want to display the counter for the start of the meeting :-)

**Comment by Blann** [comment]
It's difficult (I won't say impossible because Antony may know of a way, but I know it's awkward at best) to overlay anything on the JW Library media window without it disappearing - try moving another window on to your 2nd monitor while the yeartext is being displayed and you'll see it minimize automatically. It'll do that whenever anything else opens on that monitor - baked-in Windows 10 UWP feature, unfortunately. OnlyM can restore it automatically when you end display but obviously in that scenario the display is not actually being used simultaneously by the two apps.

**Comment by asgardi01** [comment]
Of course it could be a workaround to move and minimize windows to display the meeting counter before the beginning.
But I have the issue, that most of our brothers are not so much into computers - so it has to be very easy to handle :-)
Let me explain my idea / wish using a timeline:
6:30 PM - starting the JWL - year text appears on the 2nd screen.
-> Also starting onlyT and onlyM - still the year text of JWL is displayed on 2nd screen.
6:55 PM - the countdown of onlyT starts - the year text window gets automatically minimized and the onlyT countdown appears. 
7:00 PM - countdown of onlyT finished. onlyT window gets minimized and JWL year text window gets displayed again.

That would be a very comfortable handling also for my brothers - if they would have to move windows or mini-/maximize windows by themselves, it will not work ;-)

It seems to me, that onlyM uses a similar "trick" or function to display images even if the JWL 2nd screen is active by just minimizing the JWL window and bringing it back up after the onlyM action is finished.
Maybe one of the devs could imagine a way to make this possible :-)

By the way - Let me give a big THANK YOU! to the devs, who put a lot of effort in developing this really very useful tools for us!!! :-D

**Comment by AntonyCorbett** [comment]
@asgardi01 Thanks for your suggestion. It has been discussed before in one of the issues (now closed). My current feeling is that since the written instructions from the branch stipulate that the media monitors should display the year text before and after the meeting it would be unwise to make it easy for OnlyT to display a pre-meeting countdown on the media monitors. I may change my mind in the future, but in matters like this I generally err on the side of caution! Keep the ideas coming - thanks again.

**Comment by buzzboy360** [comment]
I cannot find the direction that the year text be displayed before and after the meeting. I'm only a servant, so I do not have access to everything.
